Bumping debian-base tag to v1.3.0
kubernetes/release pull request #1835
Opened 2021-01-09 00:42 UTC by wespanther

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This is just a periodic bump of the Debian base image tag to buster-v1.3.0 in order to take the latest upstream Debian, and all the fixes that come with it.

#### Which issue(s) this PR fixes:

None, just a number of medium to low severity CVEs.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-01-09 00:54 UTC, wespanther commented
I should note, I built this locally with:

```bash
wpanther@wpanther local/google/home/wpanther/kubernetes/release (bump-debian-base) » make build IMAGE_VERSION=buster-v1.3.0
```

And tested it came up manually like this:

```bash
wpanther@wpanther local/google/home/wpanther/kubernetes/release (bump-debian-base) » docker run --rm -it gcr.io/wpanther-gke-dev/debian-base-amd64:buster-v1.3.0 sh
# whoami
root
#
```

2021-01-09 00:55 UTC, justaugustus requested changes
@wespanther -- This will need a corresponding update to dependencies.yaml: https://github.com/kubernetes/release/blob/92087fa17d9a43c2dc19924a3dcbfa87f0f149d6/dependencies.yaml#L154.

Note that we're out for the week, so image promotion won't happen until next week.
/ok-to-test

2021-01-09 01:28 UTC, wespanther commented
@justaugustus good catch! I think I'll need this one as well:

https://github.com/kubernetes/release/blob/92087fa17d9a43c2dc19924a3dcbfa87f0f149d6/images/build/debian-base/variants.yaml#L4

Went ahead and added that.

2021-01-09 01:31 UTC, justaugustus commented
> @justaugustus good catch! I think I'll need this one as well:
> 
> https://github.com/kubernetes/release/blob/92087fa17d9a43c2dc19924a3dcbfa87f0f149d6/images/build/debian-base/variants.yaml#L4
> 
> Went ahead and added that.

Yep, yep! Thanks for this!
/lgtm
/approve

FYI @kubernetes/release-engineering -- if any of you are interesting in working on the image promotion, let me know and we can discuss next week.

2021-01-09 01:35 UTC, justaugustus commented
Note for future reference: given this is a releng repo, this PR should have a release note as it represents a change that we'd want to reflect in our next release.
(I've already backfilled one.)

2021-01-09 01:49 UTC, merged

2021-01-11 18:09 UTC, wespanther commented
> (I've already backfilled one.)

Thanks Stephen!