kube-cross: Adds mingw-w64 for Windows binary compilation
kubernetes/release pull request #1978
Opened 2021-03-26 18:14 UTC by claudiubelu

#### What type of PR is this?

/kind feature
/sig windows

#### What this PR does / why we need it:

For compiling Windows binaries, we're typically using the docker image ``dockcross/windows-static-x64``, which is currently hosted on dockerhub.

Adding the ``mingw-w64`` package into the ``kube-cross`` image will allow us to use it for Windows binaries as well, so we won't have to rely on any docker image. Because we won't have to pull another image, this will also speed up the building process of some images (e.g: pause image).

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

2021-04-07 11:22 UTC, claudiubelu commented
/cc @spiffxp

2021-04-12 19:10 UTC, jsturtevant commented
I tested this with https://github.com/kubernetes/kubernetes/pull/100592

/lgtm

2021-04-16 01:40 UTC, justaugustus requested changes
@claudiubelu -- Just one nit on the image version!

2021-04-16 01:40 UTC, justaugustus commented on images/build/cross/Makefile
> +IMAGE_VERSION ?= v1.16.2-1
```suggestion
IMAGE_VERSION ?= v1.16.1-2
```

2021-04-16 01:43 UTC, justaugustus commented on images/build/cross/Makefile
> +IMAGE_VERSION ?= v1.16.2-1
(I'll push a fix for this)

2021-04-16 01:49 UTC, justaugustus approved these changes
Thanks @claudiubelu!
/area dependency

2021-04-16 03:19 UTC, justaugustus commented
/test pull-release-integration-test

2021-04-16 03:30 UTC, merged