add go-runner to debian-iptables image
kubernetes/release pull request #2301
Opened 2021-11-02 17:58 UTC by BenTheElder

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds the go-runner binary from the go-runner image to debian-iptables.

See background: https://github.com/kubernetes/kubernetes/issues/106086

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
debian-iptables image now contains /go-runner binary
```

2021-11-02 17:59 UTC, BenTheElder commented on dependencies.yaml
> +      match: GORUNNER_VERSION \?= v\d+.\d+.\d+
this needs correcting.

2021-11-02 19:54 UTC, BenTheElder commented
> time="2021-11-02T19:12:37Z" level=info msg="Hit the rate limit on try 1, sleeping for 30m11.860280378s" err="GET https://api.github.com/repos/kubernetes/kubernetes/tags?page=12&per_page=50: 403 API rate limit of 60 still exceeded until 2021-11-02 19:42:49 +0000 UTC, not making remote request. [rate reset in 30m12s]"

unrelated flake.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2301/pull-release-integration-test/1455613165369823232
/retest

2021-11-04 19:35 UTC, pohly commented
This looks good to me, but I am not familiar with these build rules. Can someone help to get this merged?

While working on https://github.com/kubernetes/kubernetes/issues/106103 I learned that the current kubemark binary needs a libc, so it can't use the existing go-runner image. debian-iptables sounds like a suitable base image.

2021-11-07 19:40 UTC, puerco commented
Thanks Ben!
/lgtm
/approve

2021-11-07 19:45 UTC, justaugustus requested changes
/hold we need to bump the debian-iptables image version here as well

2021-11-08 14:38 UTC, dims commented
/lgtm
/approve

2021-11-08 17:02 UTC, BenTheElder commented
will fix that later today!

2021-11-09 22:09 UTC, pohly commented
@justaugustus is this okay now? If yes, please cancel the hold and LGTM.

It looks okay to me, but I don't know this area.

2021-11-10 01:09 UTC, justaugustus requested changes
@BenTheElder -- I've added some code suggestions to update to go1.17.3, now that it's out (https://github.com/kubernetes/release/pull/2305).

I'll commit them and get this merged as soon as I hit submit on this review 🙃

2021-11-10 01:09 UTC, justaugustus commented on dependencies.yaml
> +    version: v2.3.1-go1.17.2-buster.0
```suggestion
    version: v2.3.1-go1.17.3-buster.0
```

2021-11-10 01:09 UTC, justaugustus commented on images/build/debian-iptables/Makefile
> +GORUNNER_VERSION ?= v2.3.1-go1.17.2-buster.0
```suggestion
GORUNNER_VERSION ?= v2.3.1-go1.17.3-buster.0
```

2021-11-10 01:12 UTC, justaugustus approved these changes
/hold cancel

2021-11-10 01:23 UTC, merged

2021-11-10 07:28 UTC, pohly commented on images/build/debian-iptables/buster/Dockerfile
> +ARG GORUNNERIMAGE
Hmm, now that I look at how this is getting used in k/k master I realize that a similar change is probably also needed for bullseye/Dockerfile, right?

Let me try to come up with a PR...

2021-11-10 19:27 UTC, BenTheElder commented
Thanks folks (also https://github.com/kubernetes/release/pull/2310)