WIP: Integrate container image signing in `krel stage`
kubernetes/release pull request #2397
Opened 2022-01-19 16:08 UTC by saschagrunert

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Pushed images and manifest lists on stage are now signed by using the release-sdk.
#### Which issue(s) this PR fixes:

Refers to #2383 
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Added container image signing for intermediate container images produced by `krel stage`
```

2022-01-19 16:11 UTC, saschagrunert commented on pkg/release/images.go
> +func (*defaultCommandClient) Sign(signer *sign.Signer, reference string) error {
We could find a better name for this interface

2022-01-19 16:12 UTC, saschagrunert commented on pkg/release/images.go
> +		if err := i.client.Sign(signer, imageVersion); err != nil {
`imageVersion` could be `manifest`

2022-03-02 05:53 UTC, puerco requested changes
Nice work @saschagrunert !
As we made some changes to the project hosting the signer accounts, please update the service accounts in these two:

2022-03-04 08:51 UTC, saschagrunert commented
Switched to sigs.k8s.io/release-sdk v0.7.0 since this PR got a lgtm.

2022-03-04 08:55 UTC, cpanato approved these changes
/lgtm

2022-03-08 07:21 UTC, puerco commented
/test pull-release-verify

2022-03-13 03:48 UTC, puerco commented
Thank you @saschagrunert !!!
I've rebased your branch and [ran a test run of staging](https://console.cloud.google.com/cloud-build/builds;region=global/54598f84-6a29-4b4c-a92b-fd8d09f0258b?project=kubernetes-release-test) now that we have the permissions in place. I am happy to report that the staged images are signed! :tada::tada::tada::tada:

/lgtm
/approve

![image](https://user-images.githubusercontent.com/3935899/158044215-69e758b4-5c82-494a-9c29-2f5b55fc685e.png)

2022-03-13 03:51 UTC, puerco commented
/hold cancel

2022-03-13 03:52 UTC, merged

2022-03-14 08:05 UTC, saschagrunert commented
Thanks for merging @puerco! :pray: