Replaced pkg/errors dependency
kubernetes/release pull request #2553
Opened 2022-06-09 15:13 UTC by Debanitrkl

#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it
Using the native error wrapping feature to omit the direct github.com/pkg/errors dependency.
for https://github.com/kubernetes/release/tree/master/cmd/ci-reporter
#### Which issue(s) this PR fixes:

Refers to: #2549 
#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```Release Notes
None

```

2022-06-09 16:30 UTC, leonardpahlke commented
Hey @Debanitrkl thanks for opening the PR! :) the code does not compile atm (typo `root.go`) & the release notes comment is not formatted correct. 

Btw, you can check your modifications with `make verify` locally before creating the PR to insure that the test passes :). If you need support feel free to reach out any time :)!

2022-06-09 16:32 UTC, leonardpahlke requested changes

2022-06-10 04:14 UTC, Debanitrkl commented
/release-note-none

2022-06-16 10:59 UTC, saschagrunert commented
CI is still not happy :)

2022-06-16 11:17 UTC, leonardpahlke commented on cmd/ci-reporter/cmd/github.go
> +
You need to remove this page break “\n”

2022-06-16 13:20 UTC, saschagrunert approved these changes

2022-06-16 13:22 UTC, merged