newer golang patch (1.22.7, 1.23.0) sep2024
kubernetes/release pull request #3758
Opened 2024-09-12 18:11 UTC by haitch

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
- Build Go 1.22.6 images for currently supported Kubernetes release branches
- Build Go 1.23.1 images for currently supported Kubernetes release branches

#### Which issue(s) this PR fixes:

```release-note

```

2024-09-14 06:28 UTC, zhangguanzhang commented
also need for https://github.com/kubernetes/release/blob/master/images/build/distroless-iptables/Makefile#L24

2024-09-16 13:09 UTC, ameukam commented
cc @cpanato

2024-09-17 08:20 UTC, xmudrii requested changes
You also need to update `dependencies.yaml`.

You can take a look at https://github.com/kubernetes/release/pull/3724 as an inspiration how the initial Go update step looks like.

Thank you for the contribution!

2024-09-17 08:20 UTC, xmudrii commented on images/build/go-runner/Makefile
You also need to update `images/build/go-runner/Makefile`

2024-09-17 08:20 UTC, xmudrii commented on images/k8s-cloud-builder/variants.yaml
This should be updated in a dedicated step, after kubernetes/kubernetes is updated to the latest patch releases. Please drop changes to this file as of now

2024-09-17 08:20 UTC, xmudrii commented on images/releng/k8s-ci-builder/variants.yaml
This should be updated in a dedicated step, after kubernetes/kubernetes is updated to the latest patch releases. Please drop changes to this file as of now

2024-09-17 17:39 UTC, cpanato commented
I will review this PR this week, most likely tomorrow

/hold

2024-09-17 17:40 UTC, cpanato commented
also please rebase and squash the commits

2024-09-17 17:44 UTC, haitch commented
thanks for the review @xmudrii @cpanato , working on the rebase now.

2024-09-17 17:56 UTC, haitch commented
need ok-to-test label

2024-09-17 18:25 UTC, xmudrii commented
/ok-to-test

2024-09-17 23:23 UTC, haitch commented
/retest-required

2024-09-18 08:42 UTC, xmudrii commented
We hit the quota on the kube-cross test
/retest

2024-09-18 08:44 UTC, xmudrii commented
/release-note-edit
```release-note
Build Go 1.23.1 and 1.22.7 images
```

2024-09-18 08:45 UTC, xmudrii commented
/label tide/merge-method-squash

2024-09-19 10:03 UTC, cpanato commented
/unhold

2024-09-19 10:04 UTC, merged